<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Actions Namespace
    |--------------------------------------------------------------------------
    |
    | This value defines the namespace where your action classes will be
    | generated. This should match your application's Actions directory.
    |
    */

    'actions_namespace' => 'App\\Actions',

    /*
    |--------------------------------------------------------------------------
    | Actions Path
    |--------------------------------------------------------------------------
    |
    | This value defines the path where your action classes will be generated.
    | By default, this is the app/Actions directory.
    |
    */

    'actions_path' => app_path('Actions'),

    /*
    |--------------------------------------------------------------------------
    | Model Namespace
    |--------------------------------------------------------------------------
    |
    | This value defines the default namespace for your models. The command
    | will look for models in this namespace when validating model existence.
    |
    */

    'model_namespace' => 'App\\Models',

    /*
    |--------------------------------------------------------------------------
    | Pagination Per Page
    |--------------------------------------------------------------------------
    |
    | This value defines the default number of items per page for paginated
    | index actions. This can be overridden per-action.
    |
    */

    'pagination_per_page' => env('PAGINATION_PER_PAGE', 20),

    /*
    |--------------------------------------------------------------------------
    | Default Action Types
    |--------------------------------------------------------------------------
    |
    | This array defines the action types that will be generated by default
    | when running the make:actions command without specifying specific actions.
    |
    */

    'default_actions' => [
        'Index',
        'Show',
        'Store',
        'Update',
        'Delete',
    ],

    /*
    |--------------------------------------------------------------------------
    | Bulk Action Types
    |--------------------------------------------------------------------------
    |
    | This array defines the bulk action types available for generation
    | when using the --bulk option with the make:actions command.
    |
    */

    'bulk_actions' => [
        'BulkDelete',
        'BulkUpdate',
    ],

    /*
    |--------------------------------------------------------------------------
    | Cache Configuration
    |--------------------------------------------------------------------------
    |
    | Configure caching behavior for actions that use the Cacheable trait.
    | Enable caching globally and set default TTL (time-to-live in minutes).
    |
    */

    'cache' => [
        'enabled' => env('MODEL_ACTIONS_CACHE_ENABLED', false),
        'ttl' => env('MODEL_ACTIONS_CACHE_TTL', 60),
        'prefix' => 'model_actions',
    ],

];
